name: Bazel Test
on:
  push:
    branches:
      - main
jobs:
  bazel-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel-ubuntu-latest
      - run: bazel build //...
      - run: bazel test //...
