name: Make Build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get install -y \
            libnuma-dev           \
            ${{ matrix.compiler }}

      - name: Build everything
        run: make -j MACHINE=linux_${{ matrix.compiler }}_x86_64
